export const allRecipes = [
  {
    id: 1,
    title: "Carmel Apple Pie",
    description: "Treat time.", // Short desc for cards
    detailedDesc: "A decadent, warm treat featuring tart apples smothered in a rich, buttery caramel sauce, all encased in a flaky, golden-brown crust.", // Long desc for page
    ingredients: [
      { item: "Apple", amount: "4", unit: "large" },
      { item: "Caramel", amount: "1/2", unit: "cup" },
      { item: "Milk", amount: "2", unit: "tbsp" },
      { item: "Flour", amount: "2", unit: "cups" },
      { item: "Butter", amount: "1", unit: "cup" }
    ],
    steps: [
      { text: "Core, peel, and slice the apples into even wedges." },
      { text: "Prepare the pie crust by mixing flour and chilled butter until crumbly." },
      { text: "Toss apples with caramel and milk before filling the crust." },
      { text: "BOMBOCLATT." },
      { text: "BOMBOCLATT." },
      { text: "BOMBOCLATT." },
      { text: "BOMBOCLATT." },
      { text: "BOMBOCLATT." },
      { text: "BOMBOCLATT." },
      { text: "BOMBOCLATT." },
      { text: "BOMBOCLATT." },
      { text: "BOMBOCLATT." },
      { text: "BOMBOCLATT." },
      { text: "BOMBOCLATT." },
      { text: "BOMBOCLATT." },
      { text: "BOMBOCLATT." }
    ],
    cal: 480,
    p: 8,
    c: 80,
    f: 3.28,
    time: 150,
  },
  {
    id: 2,
    title: "Citrus Salmon and Asparagus",
    description: "Lemon garlic salmon.",
    ingredients: ["Salmon", "Asparagus", "Lemon", "Butter", "Garlic"],
    cal: 250,
    p: 32,
    c: 5.55,
    f: 1.69,
    time: 15,
  },
  {
    id: 3,
    title: "Feta-stuffed Hamburger",
    description: "Mediterranean twist.",
    ingredients: ["Beef", "Feta", "Onion", "Garlic", "Spinach"],
    cal: 390,
    p: 24,
    c: 1.67,
    f: 0.04,
    time: 20,
  },
  {
    id: 4,
    title: "Herbed Chicken With Roast Potatos",
    description: "Classic hearty meal.",
    ingredients: ["Chicken", "Potato"],
    cal: 470,
    p: 36,
    c: 77,
    f: 14,
    time: 40,
  },
  {
    id: 5,
    title: "Tuna-Stuffed Baked Peppers with Cheddar",
    description: "Seafood twist on stuffed peppers.",
    ingredients: ["Bell Peppers", "Tuna", "Cheddar"],
    cal: 250,
    p: 36,
    c: 14,
    f: 2.16,
    time: 20,
  },
  {
    id: 6,
    title: "Meatloaf",
    description: "It's a loaf. Of meat.",
    ingredients: ["Beef", "Tomato paste", "Breadcrumbs"],
    cal: 500,
    p: 33,
    c: 14,
    f: 2.16,
    time: 70,
  },
  {
    id: 7,
    title: "Bacon Parmesean Carbonara",
    description: "Pasta with a white bacon sauce.",
    ingredients: ["Pasta", "Milk", "Bacon", "Parmesean"],
    cal: 460,
    p: 30,
    c: 24,
    f: 2.81,
    time: 20,
  },
  {
    id: 8,
    title: "Chicken Curry",
    description: "Rice with a spiced chicken sauce.",
    ingredients: ["Rice", "Chicken"],
    cal: 390,
    p: 27,
    c: 11,
    f: 3.44,
    time: 30,
  },
  {
    id: 9,
    title: "Beef and Barley Stew",
    description: "Rich beef stew with barley.",
    ingredients: ["Beef", "Barley"],
    cal: 380,
    p: 40,
    c: 44,
    f: 8,
    time: 380,
  },
  {
    id: 10,
    title: "Steak Diane",
    description: "Steak cooked with a brandy sauce.",
    ingredients: ["Beef", "Brandy", "Mushrooms"],
    cal: 710,
    p: 63,
    c: 7,
    f: 1.23,
    time: 30,
  },
  {
    id: 11,
    title: "BBQ Glazed Pork Chops",
    description: "Pork chops glazed in a savory BBQ sauce.",
    ingredients: ["Pork", "BBQ sauce"],
    cal: 280,
    p: 44,
    c: 15,
    f: 0.47,
    time: 30,
  },
  {
    id: 12,
    title: "Protein Shake",
    description: "Protein shake base that can work with many ingredients.",
    ingredients: ["Milk", "Whey"],
    cal: 1100,
    p: 220,
    c: 27,
    f: 8,
    time: 10,
  },
  {
    id: 13,
    title: "Basalmic Chicken with Mushrooms",
    description: "Chicken baked in a basalmic glaze.",
    ingredients: ["Chicken", "Basalmic Vinegar"],
    cal: 320,
    p: 55,
    c: 2.73,
    f: 0.59,
    time: 25,
  },
  {
    id: 14,
    title: "Chicken Salad",
    description: "Salad with chicken for extra protein.",
    ingredients: ["Chicken", "Lettuce", "Cranberries"],
    cal: 230,
    p: 27,
    c: 6,
    f: 0.67,
    time: 47,
  },
  {
    id: 15,
    title: "Sweet and Sour Chicken",
    description: "Classic chicken recipe.",
    ingredients: ["Chicken", "Lemon Juice", "Rice"],
    cal: 370,
    p: 50,
    c: 22,
    f: 1.91,
    time: 30,
  },
  {
    id: 16,
    title: "Spaghetti Bolognaise",
    description: "Classic spaghetti recipe.",
    ingredients: ["Spaghetti", "Milk", "Cheese", "Tomato"],
    cal: 520,
    p: 33,
    c: 18,
    f: 7,
    time: 85,
  },
  {
    id: 17,
    title: "Beef, Mushroom, & Cilantro Soup",
    description: "Rich and Savory soup.",
    ingredients: ["Beef", "Mushroom", "Cilantro"],
    cal: 300,
    p: 27,
    c: 27,
    f: 0.77,
    time: 30,
  },
  {
    id: 18,
    title: "Chicken with Mushroom Sauce",
    description: "Chicken breasts in a mushroom cream sauce.",
    ingredients: ["Chicken", "Mushroom"],
    cal: 410,
    p: 36,
    c: 6,
    f: 1.04,
    time: 35,
  },
  {
    id: 19,
    title: "Shrimp Fettucine Alfredo",
    description: "Pasta with a cream sauce and sauted shrimp.",
    ingredients: ["Pasta", "Shrimp"],
    cal: 770,
    p: 45,
    c: 100,
    f: 4.4,
    time: 30,
  },
  {
    id: 20,
    title: "Crustless Quiche",
    description: "Egg based pastry.",
    ingredients: ["Onion", "Egg"],
    cal: 170,
    p: 36,
    c: 12,
    f: 1.88,
    time: 65,
  },
  {
    id: 256,
    title: "Five Hundred Cigarettes",
    description: "A lot of tobacco.",
    ingredients: ["Tobacco"],
    cal: -5000,
    p: 0,
    c: 0,
    f: 3,
    time: 0,
  },
];

export const ingredientOptions = ["Beef", "Chicken", "Pork", "Tofu", "Butter"];