export const allRecipes = [
  {
    id: 1,
    title: "Carmel Apple Pie",
    description: "Treat time.", // Short desc for cards
    detailedDesc: "A decadent, warm treat featuring tart apples smothered in a rich, buttery caramel sauce, all encased in a flaky, golden-brown crust.", // Long desc for page
    ingredients: [
      { item: "White Flour", amount: "1/2", unit: "cup" },
      { item: "Self-Raising Flour", amount: "1/2", unit: "cup" },
      { item: "Corn Flour", amount: "1/2", unit: "cup" },
      { item: "Butter", amount: "1/2", unit: "cup" },
      { item: "Sugar", amount: "1/3", unit: "cup" },
      { item: "Egg Yolk", amount: "6", unit: "seperated" },
      { item: "Apple", amount: "4", unit: "large" },
      { item: "Cinnamon", amount: "1", unit: "tsp" },
      { item: "Milk", amount: "2", unit: "cup" },
      { item: "Brown Sugar", amount: "1", unit: "cup" },
      { item: "Vanilla Extract", amount: "1/3", unit: "cup" },
      { item: "Vanilla Extract", amount: "2", unit: "tsp" },
    ],
    steps: [
      { text: "Preheat the oven to 375 F" },
      { text: "Combine the three flours in a bowl." },
      { text: "Add the butter, sugar, and mix well." },
      { text: "Add the eggs and gently mix the dough." },
      { text: "Knead the dough and and refridgerate for at least 30 minutes" },
      { text: "to make the filling: peel, core, and slice the apples." },
      { text: "Toss the apples with lemon and cinnamon and set them aside." },
      { text: "To make the caramel: heat the milk in a saucepan until it simmers. (do not boil)" },
      { text: "In another pan, melt the brown sugar and butter until a caramel forms." },
      { text: "Slowly pour in the milk, stiring the entire time." },
      { text: "Add the remaining vanilla extract." },
      { text: "To assemble the pie: roll out the dough, and place it into a pie tin, trimming off the excess." },
      { text: "Layer the apples into the tin evenly." },
      { text: "Pour the caramel over the apples." },
      { text: "Bake for 45-50 minutes, or until the crust is golden brown." }
    ],
    cal: 480,
    p: 8,
    c: 80,
    f: 3.28,
    time: 150,
  },
  {
    id: 2,
    title: "Citrus Salmon and Asparagus",
    description: "Lemon garlic salmon.",
    ingredients: [
      { item: "Salmon", amount: "2", unit: "filets" },
      { item: "Asparagus", amount: "10", unit: "pieces" },
      { item: "Lemon", amount: "1/4", unit: "lemon" },
      { item: "Butter", amount: "1/2", unit: "cup" },
      { item: "Garlic", amount: "3", unit: "cloves" },
    ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 250,
    p: 32,
    c: 5.55,
    f: 1.69,
    time: 15,
  },
  {
    id: 3,
    title: "Feta-stuffed Hamburger",
    description: "Mediterranean twist.",
    ingredients: [
      { item: "Beef", amount: "1", unit: "pound" },
      { item: "Feta Cheese", amount: "100", unit: "grams" },
      { item: "Spinach", amount: "1/4", unit: "pounds" },
      { item: "Garlic", amount: "3", unit: "cloves" },
    ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 390,
    p: 24,
    c: 1.67,
    f: 0.04,
    time: 20,
  },
  {
    id: 4,
    title: "Herbed Chicken With Roast Potatos",
    description: "Classic hearty meal.",
    ingredients: [
      { item: "Chicken", amount: "4", unit: "breasts" },
      { item: "Potato", amount: "5", unit: "pieces" },
      ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 470,
    p: 36,
    c: 77,
    f: 14,
    time: 40,
  },
  {
    id: 5,
    title: "Tuna-Stuffed Baked Peppers with Cheddar",
    description: "Seafood twist on stuffed peppers.",
    ingredients: [
      { item: "Bell Pepper", amount: "2", unit: "pieces" },
      { item: "Tuna", amount: "1", unit: "can" },
      { item: "Cheddar", amount: "100", unit: "grams" },
    ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 250,
    p: 36,
    c: 14,
    f: 2.16,
    time: 20,
  },
  {
    id: 6,
    title: "Meatloaf",
    description: "It's a loaf. Of meat.",
    ingredients: [
      { item: "Beef", amount: "1", unit: "pound" },
      { item: "Tomato paste", amount: "1", unit: "can" },
      { item: "Breadcrumbs", amount: "1/2", unit: "cup" },
    ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 500,
    p: 33,
    c: 14,
    f: 2.16,
    time: 70,
  },
  {
    id: 7,
    title: "Bacon Parmesean Carbonara",
    description: "Pasta with a white bacon sauce.",
    ingredients: [
      { item: "Pasta", amount: "1", unit: "pack" },
      { item: "Milk", amount: "1", unit: "cup" },
      { item: "Bacon", amount: "1/3", unit: "pound" },
      { item: "Parmesean Cheese", amount: "1/3", unit: "pound" },
    ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 460,
    p: 30,
    c: 24,
    f: 2.81,
    time: 20,
  },
  {
    id: 8,
    title: "Chicken Curry",
    description: "Rice with a spiced chicken sauce.",
    ingredients: [
      { item: "Rice", amount: "2", unit: "cups" },
      { item: "Chicken", amount: "3", unit: "Pieces" },
    ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 390,
    p: 27,
    c: 11,
    f: 3.44,
    time: 30,
  },
  {
    id: 9,
    title: "Beef and Barley Stew",
    description: "Rich beef stew with barley.",
    ingredients: [
      { item: "Beef", amount: "1/2", unit: "pound" },
      { item: "Barley", amount: "1/4", unit: "cup" },
    ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 380,
    p: 40,
    c: 44,
    f: 8,
    time: 380,
  },
  {
    id: 10,
    title: "Steak Diane",
    description: "Steak cooked with a brandy sauce.",
    ingredients: [
      { item: "Beef Steak", amount: "1", unit: "piece" },
      { item: "Brandy", amount: "1/4", unit: "cup" },
      { item: "Mushrooms", amount: "4", unit: "pieces" },
    ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 710,
    p: 63,
    c: 7,
    f: 1.23,
    time: 30,
  },
  {
    id: 11,
    title: "BBQ Glazed Pork Chops",
    description: "Pork chops glazed in a savory BBQ sauce.",
    ingredients: [
      { item: "Pork Chops", amount: "2", unit: "pieces" },
      { item: "BBQ sauce", amount: "1/4", unit: "cup" },
    ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 280,
    p: 44,
    c: 15,
    f: 0.47,
    time: 30,
  },
  {
    id: 12,
    title: "Protein Shake",
    description: "Protein shake base that can work with many ingredients.",
    ingredients: [
      { item: "Milk", amount: "1", unit: "cup" },
      { item: "Whey", amount: "1/2", unit: "cup" },
    ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 1100,
    p: 220,
    c: 27,
    f: 8,
    time: 10,
  },
  {
    id: 13,
    title: "Basalmic Chicken with Mushrooms",
    description: "Chicken baked in a basalmic glaze.",
    ingredients: [
      { item: "Chicken", amount: "2", unit: "pieces" },
      { item: "Mushrooms", amount: "3", unit: "pieces" },
      { item: "Basalmic vineger", amount: "1/3", unit: "cup" },
    ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 320,
    p: 55,
    c: 2.73,
    f: 0.59,
    time: 25,
  },
  {
    id: 14,
    title: "Chicken Salad",
    description: "Salad with chicken for extra protein.",
    ingredients: [
      { item: "Chicken", amount: "2", unit: "pieces" },
      { item: "Lettuce", amount: "1/3", unit: "head" },
      { item: "Cranberries", amount: "1/2", unit: "cup" },
    ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 230,
    p: 27,
    c: 6,
    f: 0.67,
    time: 47,
  },
  {
    id: 15,
    title: "Sweet and Sour Chicken",
    description: "Classic chicken recipe.",
    ingredients: [
      { item: "Chicken", amount: "3", unit: "pieces" },
      { item: "Lemon Juice", amount: "1/2", unit: "cup" },
      { item: "Rice", amount: "2", unit: "cups" },
    ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 370,
    p: 50,
    c: 22,
    f: 1.91,
    time: 30,
  },
  {
    id: 16,
    title: "Spaghetti Bolognaise",
    description: "Classic spaghetti recipe.",
    ingredients: [
      { item: "Pasta", amount: "1", unit: "pack" },
      { item: "Milk", amount: "1", unit: "cup" },
      { item: "Tomato Paste", amount: "1", unit: "can" },
      { item: "Cheese", amount: "1/3", unit: "pound" },
    ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 520,
    p: 33,
    c: 18,
    f: 7,
    time: 85,
  },
  {
    id: 17,
    title: "Beef, Mushroom, & Cilantro Soup",
    description: "Rich and Savory soup.",
    ingredients: [
      { item: "Beef", amount: "1/2", unit: "pound" },
      { item: "Mushroom", amount: "5", unit: "pieces" },
      { item: "Cilantro", amount: "20", unit: "grams" },
    ],    
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 300,
    p: 27,
    c: 27,
    f: 0.77,
    time: 30,
  },
  {
    id: 18,
    title: "Chicken with Mushroom Sauce",
    description: "Chicken breasts in a mushroom cream sauce.",
    ingredients: [
      { item: "Chicken", amount: "2", unit: "pieces" },
      { item: "Mushroom", amount: "5", unit: "pieces" },
    ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 410,
    p: 36,
    c: 6,
    f: 1.04,
    time: 35,
  },
  {
    id: 19,
    title: "Shrimp Fettucine Alfredo",
    description: "Pasta with a cream sauce and sauted shrimp.",
    ingredients: [
      { item: "Pasta", amount: "1", unit: "pack" },
      { item: "Milk", amount: "1", unit: "cup" },
      { item: "Shrimp", amount: "1", unit: "cup" },
      { item: "Parmesean Cheese", amount: "1/3", unit: "pound" },
    ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 770,
    p: 45,
    c: 100,
    f: 4.4,
    time: 30,
  },
  {
    id: 20,
    title: "Crustless Quiche",
    description: "Egg based pastry.",
    ingredients: ["Onion", "Egg"],
    ingredients: [
      { item: "Egg", amount: "4", unit: "eggs" },
      { item: "Onion", amount: "1/2", unit: "chopped" },
    ],
    steps: [
      { text: "Placeholder 1" },
      { text: "Placeholder 2" },
      { text: "Placeholder 3" },
    ],
    cal: 170,
    p: 36,
    c: 12,
    f: 1.88,
    time: 65,
  },
  {
    id: 256,
    title: "Five Hundred Cigarettes",
    description: "A lot of tobacco.",
ingredients: [
      { item: "Marlobro Red", amount: "25", unit: "cartons" },
    ],
    steps: [
      { text: "Open all the cartons of cigarettes, and place them on a plate" },
      { text: "Smoke them" },
      { text: "(Fridge thing is not responsable for any health issues or other problems caused by following these recipes)"}
    ],
    cal: -5000,
    p: 0,
    c: 0,
    f: 3,
    time: 0,
  },
];

export const ingredientOptions = ["Beef", "Chicken", "Pork", "Tofu", "Butter"];